### PR TITLE
Fix: empty whitelist should permit all jobs

### LINKED ISSUE #102: Empty whitelist does not permit all jobs
Plugin 0.6.1
Jenkins 2.60.3

Upon upgrading to 0.6.1 we found all metrics apart from `jenkins.queue.size` missing from DataDog. To enable metrics again we had to specify all job names in the whitelist. This should not be the case according to the docs.

Thanks

### PR DESCRIPTION
**Pull request by nikola-da**
We've encountered issue #102 and this is a fix we applied and tested.

Fixes #102

### CODE REVIEW

**Comment by sjenriquez** [comment]
@nikola-da Thank you for submitting this PR! We'll review as soon as possible.

**Comment by nikola-da** [comment]
Cool! Let me know if you have any questions or if I could help somehow

File: src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java [hunk 1]
```diff
@@ -115,14 +115,9 @@ public static boolean isJobTracked(final String jobName) {
...
-    final String[] blacklist = DatadogUtilities.joblistStringtoArray( DatadogUtilities.getBlacklist() );
-    final String jobNameLowerCase = jobName.toLowerCase();
-
-    if (blacklist != null) {
-      return Arrays.asList(blacklist).contains(jobNameLowerCase);
-    }
+    final List<String> blacklist = DatadogUtilities.joblistStringtoList( DatadogUtilities.getBlacklist() );
 
-    return false;
+    return blacklist.contains(jobName.toLowerCase());
```
Comment (sjenriquez) [inline src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java]: Could you remove whitespace from `jobName` here as well as lowering? When we set the whitelist and blacklist, spaces are stripped out. This would look like 
`return blacklist.contains(jobName.replaceAll("\\s", "").toLowerCase())`

File: src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java [hunk 2]
```diff
@@ -132,14 +127,9 @@ public static boolean isJobBlacklisted(final String jobName) {
...
-    final String[] whitelist = DatadogUtilities.joblistStringtoArray( DatadogUtilities.getWhitelist() );
-    final String jobNameLowerCase = jobName.toLowerCase();
+    final List<String> whitelist = DatadogUtilities.joblistStringtoList( DatadogUtilities.getWhitelist() );
 
-    if ( whitelist == null || whitelist.length == 0) {
-        return true;
-    }
-
-    return Arrays.asList(whitelist).contains(jobNameLowerCase);
+    return whitelist.isEmpty() || whitelist.contains(jobName.toLowerCase());
```
Comment (sjenriquez) [inline src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java]: Same here for whitelist:
`return whitelist.isEmpty() || whitelist.contains(jobName.replaceAll("\\s", "").toLowerCase())`

**Comment by nikola-da** [comment]
Awesome! thanks for merging in. When could we expect a release?

**Comment by sjenriquez** [comment]
We're aiming for this week @nikola-da, thanks again for the PR!
