### PR TITLE
Send delivery KPIs (fixes #130)

### LINKED ISSUE #130: Have pipeline statistics
I'd like to see pipeline statistics as mentioned in [this blog post](https://stelligent.com/2017/11/16/codepipeline-dashboard/)

Each `Job` should provide
- Lead Time
- Cycle Time
- Feedback Time
- MTTR
- MTBF

Fail 1

From [https://github.com/stelligent/pipeline-dashboard/blob/master/README.md#metric-details](https://github.com/stelligent/pipeline-dashboard/blob/master/README.md#metric-details)

What do you think, is it worth to start a PR?

### PR DESCRIPTION
**Pull request by pgarbe**
This PRs sends additional metrics to Datadog to measure the performance of teams. It's based on the  [blog post](https://stelligent.com/2017/11/16/codepipeline-dashboard/) from Stelligent.

Each `Job`  provides
- Lead Time
- Cycle Time
- Feedback Time
- MTTR
- MTBF

Fail 1

From [https://github.com/stelligent/pipeline-dashboard/blob/master/README.md#metric-details](https://github.com/stelligent/pipeline-dashboard/blob/master/README.md#metric-details)

### CODE REVIEW

**Comment by miketheman** [comment]
Looks awesome!! @sjenriquez any chance for a review soon?

**Comment by sjenriquez** [comment]
@pgarbe Thanks for the PR, will take a look shortly! cc: @miketheman

File: src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java [hunk 1]
```diff
@@ -196,6 +197,26 @@ public final void onCompleted(final Run run, @Nonnull final TaskListener listene
           statsd = getDescriptor().leaseClient();
           statsd.incrementCounter("completed", tagsToCounter);
           logger.fine(String.format("Attempted to send 'completed' counter with tags: %s", Arrays.toString(tagsToCounter)));
+
+          // Send KPIs 
+          if (!isMasterBranch(run)) {
```
Comment (sjenriquez) [inline src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java]: Why do we only want to collect metrics for `!isMasterBranch(run)`?

File: src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java [hunk 2]
```diff
@@ -196,6 +197,26 @@ public final void onCompleted(final Run run, @Nonnull final TaskListener listene
...
+
+              statsd.gauge("cycletime", cycleTime / 1000, tagsToCounter);
+              statsd.gauge("leadtime", leadTime / 1000, tagsToCounter);
+              statsd.gauge("mttr", mttr / 1000, tagsToCounter);
+            } else {
+              long feedbackTime = run.getDuration();
+              long mtbf = getMeanTimeBetweenFailure(run);
+
+              statsd.gauge("feedbacktime", feedbackTime / 1000, tagsToCounter);
+              statsd.gauge("mtbf", mtbf / 1000, tagsToCounter);
```
Comment (sjenriquez) [inline src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java]: Submitting `0` values could lead to incorrect aggregation over various timeframes. In these cases, we should only submit the metric if the value `!= 0`. Looks like this could be the case for `mttr`, `cycleTime`, and `mtbf`.

File: src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java [hunk 3]
```diff
@@ -196,6 +197,26 @@ public final void onCompleted(final Run run, @Nonnull final TaskListener listene
...
           logger.fine(String.format("Attempted to send 'completed' counter with tags: %s", Arrays.toString(tagsToCounter)));
+
+          // Send KPIs 
+          if (!isMasterBranch(run)) {
+            if (run.getResult() == Result.SUCCESS) {
+              long mttr = getMeanTimeToRecovery(run);
+              long cycleTime = getCycleTime(run);;
+              long leadTime = run.getDuration() + mttr;
+
+              statsd.gauge("cycletime", cycleTime / 1000, tagsToCounter);
```
Comment (sjenriquez) [inline src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java]: Small thing: can you rename `tagsToCounter` to something like `statsdTags`?

File: src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java (hunk 1 above)
Comment (pgarbe) [reply src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java]: These metrics make only sense when it's about a release. And my assumption is that releases happens only on the master branch. That's why it doesn't make sense to consider PR or branch builds.

File: src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java (hunk 2 above)
Comment (pgarbe) [reply src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java]: Yes, that makes sense. Will change it.

File: src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java (hunk 3 above)
Comment (pgarbe) [reply src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java]: No problem

File: src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java (hunk 1 above)
Comment (sjenriquez) [reply src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java]: Yea, I see how this is tied to code releases. We could hit issues trying to match a hardcoded `master` branch that could really limits these metrics. It's possible releases happen on branches not named `master` or some other use case with a name different from `master`. I think we'll need some options in the Job configuration page to make this flexible - a checkbox to enable/disable collection of these metrics as well as an option to specify a branch name. What are your thoughts?

Comment (miketheman) [reply src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java]: How about instead of making the branch a configuration value, tracking _all_ branches, and adding that as a tag, so that the user can then decide which ones they want to use for overlays, metrics, etc?

Comment (sjenriquez) [reply src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java]: 💯 @miketheman

Comment (pgarbe) [reply src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java]: If the branch should be added as tag, it would affect also all other metrics. Do you think that make sense?

Comment (miketheman) [reply src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java]: Maybe the branch tag should be associated with every metric, so as to allow for better analysis

Comment (sjenriquez) [reply src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java]: Apologies for not catching this earlier, but we already collect the branch tag if it exists: https://github.com/DataDog/jenkins-datadog-plugin/blob/27fc3a58014aa4a84a9c35173b7f8d254355c5e2/src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java#L314-L315

Comment (pgarbe) [reply src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java]: Thanks for the hint. Actually, I've never seen this tag in one of our metrics. Have to check why this is missing.

**Comment by srizzling** [comment]
How close is this to hitting master?

**Comment by irabinovitch** [comment]
@sjenriquez @pgarbe Thoughts on next steps?

**Comment by sjenriquez** [comment]
@irabinovitch This PR is mostly there, we can finish it up internally and get it merged.

**Comment by nmuesch** [comment]
Thanks again for this @pgarbe! I've done the requested cleanups and merged this in #132 🙇
